"""Query-construction strategies under test, and a retrieval path that can route per arm.

Production runs every query through both arms. The proposal only makes sense if a query can be
addressed at one arm -- a 200-word advert through websearch_to_tsquery ANDs every term and
returns nothing, and an exact token like "ISO 14001" is noise to a 384-d sentence encoder. So
retrieval here takes two query lists instead of one, and the strategies differ only in how they
fill them.

Budget is kept identical to production for every strategy: RETRIEVAL_LIMIT spread across the
queries of each arm, floored at MIN_PER_QUERY. That is the point of the dilution question -- a
strategy with more queries gets thinner slices, not more rows.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from trouveur.db.queries import match as match_q
from trouveur.ingest.embed import get_provider
from trouveur.match.expand import MAX_QUERIES, combine, deterministic_queries
from trouveur.match.fuse import reciprocal_rank_fusion
from trouveur.match.retrieve import MIN_PER_QUERY, RETRIEVAL_LIMIT

FIXTURES = json.loads((Path(__file__).parent / "expansions.json").read_text(encoding="utf-8"))
# The same three artifacts generated by the model production actually pins. A proposal that only
# works when a frontier model writes the adverts is a different, more expensive proposal.
_LLM_PATH = Path(__file__).parent / "expansions_llm.json"
LLM = json.loads(_LLM_PATH.read_text(encoding="utf-8")) if _LLM_PATH.exists() else None


@dataclass
class QuerySet:
    """What a strategy sends to each arm. `dense_pool` mean-pools its vectors into one query."""

    dense: list[str] = field(default_factory=list)
    lexical: list[str] = field(default_factory=list)
    dense_pool: bool = False
    # Override the per-query slice. Production divides a fixed budget by the number of queries,
    # so "more queries" and "less depth each" are the same move and their effects cannot be told
    # apart. Fixing the slice separates them: retrieval costs no money, so a design that simply
    # fetches more is allowed to be the answer.
    depth: int | None = None

    @property
    def total(self) -> int:
        return len(self.dense) + len(self.lexical)


@dataclass
class Arms:
    dense: list[list[int]] = field(default_factory=list)
    lexical: list[list[int]] = field(default_factory=list)

    @property
    def all(self) -> list[list[int]]:
        return [*self.dense, *self.lexical]


async def retrieve_routed(conn, profile, qs: QuerySet) -> Arms:
    provider = get_provider()
    dense_lists: list[list[int]] = []

    if qs.dense:
        vectors = await provider.embed_queries(qs.dense)
        if qs.dense_pool:
            # HyDE's own recipe: average the hypothetical-document vectors into one query, so the
            # budget goes deep on one list instead of thin across many near-identical ones.
            pooled = [sum(values) / len(values) for values in zip(*vectors, strict=True)]
            vectors = [pooled]
        per_query = qs.depth or max(RETRIEVAL_LIMIT // len(vectors), MIN_PER_QUERY)
        for vector in vectors:
            dense_lists.append(await match_q.dense_candidates(conn, profile, vector, per_query))

    lexical_lists: list[list[int]] = []
    if qs.lexical:
        per_query = qs.depth or max(RETRIEVAL_LIMIT // len(qs.lexical), MIN_PER_QUERY)
        for query in qs.lexical:
            lexical_lists.append(
                await match_q.lexical_candidates(conn, profile, query, per_query)
            )
    return Arms(dense=dense_lists, lexical=lexical_lists)


def fuse(arms: Arms, limit: int) -> list[int]:
    return [job_id for job_id, _ in reciprocal_rank_fusion(arms.all)[:limit]]


def _or_query(phrases: list[str]) -> str:
    """One tsquery over many titles, so the lexical arm returns one deep ranked list."""
    return " OR ".join(f'"{phrase}"' for phrase in phrases)


def build(name: str, profile, persona_key: str) -> QuerySet:
    det = deterministic_queries(profile)
    fx = FIXTURES["personas"][persona_key]
    ads, titles, tokens = fx["ads"], fx["titles"], fx["tokens"]
    # Stand-in for today's with-key expansion: the current prompt asks for 5-8 short noun phrases
    # covering synonyms and adjacent titles, which is the head of the same generated title list,
    # combined with the user's own words exactly as production's combine() does.
    phrases = combine(det, titles[:MAX_QUERIES])

    match name:
        case "det":
            return QuerySet(dense=det, lexical=det)
        case "phrases8":
            return QuerySet(dense=phrases, lexical=phrases)
        case "ads15_dense":
            return QuerySet(dense=ads, lexical=det)
        case "ads5_dense":
            return QuerySet(dense=ads[:5], lexical=det)
        case "ads3_dense":
            return QuerySet(dense=ads[:3], lexical=det)
        case "ads15_pooled":
            return QuerySet(dense=ads, lexical=det, dense_pool=True)
        case "ads15_both":
            # The naive reading of the proposal: adverts sent to both arms.
            return QuerySet(dense=ads, lexical=ads)
        case "titles30":
            return QuerySet(dense=titles, lexical=titles)
        case "titles15":
            return QuerySet(dense=titles[:15], lexical=titles[:15])
        case "titles30_or":
            return QuerySet(dense=titles, lexical=[_or_query(titles)])
        case "tokens_lex":
            return QuerySet(dense=det, lexical=[*det, *tokens])
        case "full_proposal":
            # 15 ads + 30 titles + 20 tokens, routed as proposed.
            return QuerySet(dense=[*ads, *titles], lexical=[*titles, *tokens])
        case "routed_tuned":
            # Pooled ads for depth, a single OR'd title query, tokens and the user's own words.
            return QuerySet(
                dense=[*ads, *det], lexical=[_or_query(titles), *det, *tokens], dense_pool=False
            )
        case "routed_pooled":
            return QuerySet(
                dense=ads, lexical=[_or_query(titles), *det, *tokens], dense_pool=True
            )
        # The correction the rank deltas demand: adverts ADDED to the user's own words in the
        # dense arm, not substituted for them. Substituting is what costs T1 -- the needles that
        # share the profile's vocabulary are found by the profile's vocabulary.
        case "det_plus_ads3":
            return QuerySet(dense=[*det, *ads[:3]], lexical=det)
        case "det_plus_ads5":
            return QuerySet(dense=[*det, *ads[:5]], lexical=det)
        case "det_plus_ads8":
            return QuerySet(dense=[*det, *ads[:8]], lexical=det)
        case "det_plus_ads5_deep":
            return QuerySet(dense=[*det, *ads[:5]], lexical=det, depth=200)
        # Tokens as one OR'd query rather than twenty, so the lexical budget is not split twenty
        # ways to ask twenty questions the trigram path answers in one.
        case "tokens_or":
            return QuerySet(dense=det, lexical=[*det, _or_query(tokens)])
        case "det_plus_ads5_tokens_or":
            return QuerySet(dense=[*det, *ads[:5]], lexical=[*det, _or_query(tokens)])
        case "det_plus_ads5_titles_or":
            return QuerySet(
                dense=[*det, *ads[:5]], lexical=[*det, _or_query(titles), _or_query(tokens)]
            )
        case "det_deep":
            return QuerySet(dense=det, lexical=det, depth=200)
        case "ads5_deep":
            return QuerySet(dense=ads[:5], lexical=det, depth=200)
        case "titles30_deep":
            return QuerySet(dense=titles, lexical=titles, depth=200)
        case "full_proposal_deep":
            return QuerySet(dense=[*ads, *titles], lexical=[*titles, *tokens], depth=200)
        case _ if name.startswith("llm_"):
            return _build_llm(name, det, persona_key)
        case _:
            raise ValueError(f"unknown strategy {name}")


def _build_llm(name: str, det: list[str], persona_key: str) -> QuerySet:
    fx = LLM["personas"][persona_key]
    short, long_ = fx["ads_short"], fx["ads_long"]
    v2 = fx.get("ads_v2", [])
    titles, tokens = fx["titles"], fx["tokens"]
    phrases = fx["phrases_production"]

    match name:
        # What a user with a key gets today: the current prompt, the current routing.
        case "llm_phrases":
            combined = combine(det, phrases)
            return QuerySet(dense=combined, lexical=combined)
        case "llm_ads_short":
            return QuerySet(dense=short, lexical=det)
        case "llm_ads_long":
            return QuerySet(dense=long_, lexical=det)
        case "llm_ads_short_pooled":
            return QuerySet(dense=short, lexical=det, dense_pool=True)
        case "llm_titles30_or":
            return QuerySet(dense=titles, lexical=[_or_query(titles)])
        case "llm_tokens_lex":
            return QuerySet(dense=det, lexical=[*det, *tokens])
        case "llm_full_proposal":
            return QuerySet(dense=[*short, *titles], lexical=[*titles, *tokens])
        case "llm_det_plus_ads3":
            return QuerySet(dense=[*det, *short[:3]], lexical=det)
        case "llm_det_plus_ads5":
            return QuerySet(dense=[*det, *short[:5]], lexical=det)
        case "llm_det_plus_ads8":
            return QuerySet(dense=[*det, *short[:8]], lexical=det)
        case "llm_det_plus_ads5_deep":
            return QuerySet(dense=[*det, *short[:5]], lexical=det, depth=200)
        case "llm_det_plus_ads15":
            return QuerySet(dense=[*det, *short], lexical=det)
        case "llm_ads_v2":
            return QuerySet(dense=v2, lexical=det)
        case "llm_det_plus_ads_v2":
            return QuerySet(dense=[*det, *v2], lexical=det)
        case "llm_det_plus_ads_v2_deep":
            return QuerySet(dense=[*det, *v2], lexical=det, depth=200)
        case "llm_routed_tuned":
            return QuerySet(dense=[*short, *det], lexical=[_or_query(titles), *det, *tokens])
        case _:
            raise ValueError(f"unknown strategy {name}")


STRATEGIES = [
    "det", "phrases8", "ads3_dense", "ads5_dense", "ads15_dense", "ads15_pooled", "ads15_both",
    "titles15", "titles30", "titles30_or", "tokens_lex", "full_proposal", "routed_tuned",
    "routed_pooled",
]
TUNED_STRATEGIES = [
    "det_plus_ads3", "det_plus_ads5", "det_plus_ads8", "det_plus_ads5_deep", "tokens_or",
    "det_plus_ads5_tokens_or", "det_plus_ads5_titles_or",
]
DEPTH_STRATEGIES = ["det_deep", "ads5_deep", "titles30_deep", "full_proposal_deep"]
LLM_STRATEGIES = [
    "llm_phrases", "llm_ads_short", "llm_ads_long", "llm_ads_short_pooled", "llm_titles30_or",
    "llm_tokens_lex", "llm_full_proposal", "llm_routed_tuned",
]
