"""initial schema

Written as explicit DDL rather than autogenerated: the generated tsvector column and the two GIN
indexes are the core of German search here, and autogenerate does not round-trip them reliably.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    # Installed now, unused for the moment, so that adding embedding-based similarity later is a
    # migration rather than a database port.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute("CREATE TYPE user_state AS ENUM ('new','interested','applied','rejected')")
    op.execute("CREATE TYPE rule_verdict AS ENUM ('pass','reject','unknown')")
    op.execute(
        "CREATE TYPE salary_period AS ENUM ('YEAR','MONTH','WEEK','DAY','HOUR','UNKNOWN')"
    )
    op.execute("CREATE TYPE pipeline_run_status AS ENUM ('queued','running','success','failed')")
    op.execute("CREATE TYPE pipeline_run_trigger AS ENUM ('scheduled','manual')")

    op.execute(
        """
        CREATE TABLE job (
            id               bigserial PRIMARY KEY,
            source           text NOT NULL,
            source_native_id text NOT NULL,
            url              text NOT NULL,
            title            text NOT NULL,
            company          text,
            location_city    text,
            location_country text,
            remote           boolean,
            salary_min       numeric,
            salary_max       numeric,
            salary_period    salary_period NOT NULL DEFAULT 'UNKNOWN',
            posted_at        timestamptz,
            description      text,
            raw              jsonb NOT NULL DEFAULT '{}'::jsonb,
            content_hash     bytea NOT NULL,
            search_norm      text NOT NULL DEFAULT '',
            first_seen       timestamptz NOT NULL DEFAULT now(),
            last_seen        timestamptz NOT NULL DEFAULT now(),
            rule_verdict     rule_verdict NOT NULL DEFAULT 'unknown',
            llm_score        smallint,
            llm_reason       text,
            llm_red_flags    jsonb,
            notified_at      timestamptz,
            user_state       user_state NOT NULL DEFAULT 'new',
            search_de        tsvector GENERATED ALWAYS AS (
                to_tsvector(
                    'german',
                    coalesce(title, '') || ' ' ||
                    coalesce(company, '') || ' ' ||
                    coalesce(description, '')
                )
            ) STORED,
            CONSTRAINT job_source_native_uniq UNIQUE (source, source_native_id),
            CONSTRAINT job_content_hash_uniq  UNIQUE (content_hash)
        )
        """
    )

    # Both indexes are required; see AGENTS.md > Database rules. The tsvector handles German
    # inflection, the trigram index matches inside compound nouns. Neither alone is sufficient.
    op.execute("CREATE INDEX job_search_de_idx ON job USING gin (search_de)")
    op.execute(
        "CREATE INDEX job_search_norm_trgm_idx ON job USING gin (search_norm gin_trgm_ops)"
    )
    op.execute("CREATE INDEX job_posted_at_idx ON job (posted_at DESC NULLS LAST)")
    op.execute("CREATE INDEX job_llm_score_idx ON job (llm_score DESC NULLS LAST)")
    op.execute("CREATE INDEX job_user_state_idx ON job (user_state)")

    op.execute(
        """
        CREATE TABLE profile (
            id                  smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
            version             integer NOT NULL DEFAULT 1,
            title               text NOT NULL DEFAULT '',
            years_experience    integer NOT NULL DEFAULT 0,
            languages           text[] NOT NULL DEFAULT '{}',
            objectives          text NOT NULL DEFAULT '',
            must_have           text[] NOT NULL DEFAULT '{}',
            deal_breakers       text[] NOT NULL DEFAULT '{}',
            keywords            text[] NOT NULL DEFAULT '{}',
            cities              text[] NOT NULL DEFAULT '{}',
            countries           text[] NOT NULL DEFAULT '{AT,DE,CH}',
            remote_only         boolean NOT NULL DEFAULT false,
            min_salary_eur_year numeric NOT NULL DEFAULT 0,
            notify_threshold    smallint NOT NULL DEFAULT 70,
            updated_at          timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    # Single row, created only by `trouveur create-user`. There is deliberately no registration
    # endpoint in the web app.
    op.execute(
        """
        CREATE TABLE app_user (
            id              smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
            username        text NOT NULL UNIQUE,
            password_hash   text NOT NULL,
            failed_attempts integer NOT NULL DEFAULT 0,
            locked_until    timestamptz,
            created_at      timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE source_state (
            source          text PRIMARY KEY,
            cursor          text,
            etag            text,
            last_run_at     timestamptz,
            last_success_at timestamptz,
            last_error      text,
            jobs_seen       integer NOT NULL DEFAULT 0
        )
        """
    )

    op.execute(
        """
        CREATE TABLE llm_score_cache (
            content_hash    bytea PRIMARY KEY,
            profile_version integer NOT NULL,
            score           smallint NOT NULL,
            reason          text NOT NULL,
            red_flags       jsonb NOT NULL DEFAULT '[]'::jsonb,
            model           text NOT NULL,
            created_at      timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    # Owned by the runner service: it holds the schedule and drains the queue. The web UI only
    # enqueues pipeline_run rows and reads them back.
    op.execute(
        """
        CREATE TABLE pipeline_schedule (
            id            smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
            enabled       boolean  NOT NULL DEFAULT true,
            run_hour      smallint NOT NULL DEFAULT 7 CHECK (run_hour BETWEEN 0 AND 23),
            run_minute    smallint NOT NULL DEFAULT 0 CHECK (run_minute BETWEEN 0 AND 59),
            lookback_days smallint NOT NULL DEFAULT 1 CHECK (lookback_days BETWEEN 1 AND 90),
            updated_at    timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("INSERT INTO pipeline_schedule (id) VALUES (1)")

    op.execute(
        """
        CREATE TABLE pipeline_run (
            id            bigserial PRIMARY KEY,
            trigger       pipeline_run_trigger NOT NULL,
            status        pipeline_run_status  NOT NULL DEFAULT 'queued',
            lookback_days smallint NOT NULL DEFAULT 1,
            use_llm       boolean  NOT NULL DEFAULT true,
            send_email    boolean  NOT NULL DEFAULT true,
            attempts      smallint NOT NULL DEFAULT 0,
            queued_at     timestamptz NOT NULL DEFAULT now(),
            not_before    timestamptz NOT NULL DEFAULT now(),
            started_at    timestamptz,
            finished_at   timestamptz,
            report        jsonb,
            error         text
        )
        """
    )
    # Claiming scans the queue by (status, not_before); the history view orders by queued_at.
    op.execute(
        "CREATE INDEX pipeline_run_claim_idx ON pipeline_run (not_before) "
        "WHERE status = 'queued'"
    )
    op.execute("CREATE INDEX pipeline_run_queued_at_idx ON pipeline_run (queued_at DESC)")

    # The employers Personio watches, edited in the web UI. Deliberately its own table and not a
    # profile column: adding one must not bump profile.version, which would invalidate every
    # cached LLM score. The CHECK mirrors the DNS-label shape of a Personio subdomain.
    op.execute(
        """
        CREATE TABLE personio_tenant (
            slug     text PRIMARY KEY CHECK (slug ~ '^[a-z0-9][a-z0-9-]*$'),
            enabled  boolean NOT NULL DEFAULT true,
            added_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )


def downgrade() -> None:
    for table in (
        "personio_tenant", "pipeline_run", "pipeline_schedule",
        "llm_score_cache", "source_state", "app_user", "profile", "job",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table}")
    for enum in (
        "pipeline_run_trigger", "pipeline_run_status",
        "salary_period", "rule_verdict", "user_state",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum}")
