"""Pipeline v2: raw archive, versioned derivation, per-user match overlay.

Written as explicit DDL rather than autogenerated, because the generated columns, the HNSW index
and the immutable unaccent wrapper have no SQLAlchemy expression and would be dropped by any
autogenerate pass that ran after them.

Revision ID: 0001_pipeline_v2
"""

from alembic import op

revision = "0001_pipeline_v2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # unaccent() is only STABLE, because the dictionary it consults can be reloaded, so it cannot
    # appear in a generated column or an index. Naming the dictionary explicitly makes the call
    # deterministic, which is what lets this wrapper be declared IMMUTABLE.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION f_unaccent(text) RETURNS text
            LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
        AS $$ SELECT public.unaccent('public.unaccent', $1) $$
        """
    )

    for name, values in [
        ("document_kind", "'listing','detail'"),
        ("salary_period", "'YEAR','MONTH','WEEK','DAY','HOUR','UNKNOWN'"),
        ("work_mode", "'onsite','hybrid','remote','unknown'"),
        ("seniority", "'intern','junior','mid','senior','lead','executive','unknown'"),
        ("employment_type",
         "'full_time','part_time','contract','temporary','internship','apprenticeship','unknown'"),
        ("work_kind", "'detail','derive','embed','dedup'"),
        ("rule_verdict", "'pass','reject','unknown'"),
        ("user_state", "'new','saved','applied','dismissed'"),
        ("run_status", "'queued','running','success','failed'"),
        ("run_trigger", "'scheduled','manual'"),
    ]:
        op.execute(f"CREATE TYPE {name} AS ENUM ({values})")

    op.execute(
        """
        CREATE TABLE source_document (
            id             bigserial PRIMARY KEY,
            source         text NOT NULL,
            external_id    text NOT NULL,
            kind           document_kind NOT NULL,
            scope          text,
            payload        jsonb NOT NULL,
            payload_sha256 bytea NOT NULL,
            fetched_at     timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT source_document_identity_uniq
                UNIQUE (source, external_id, kind, payload_sha256)
        )
        """
    )
    op.execute(
        "CREATE INDEX source_document_lookup_idx "
        "ON source_document (source, external_id, kind, fetched_at DESC)"
    )

    op.execute(
        """
        CREATE TABLE job (
            id                   bigserial PRIMARY KEY,
            public_id            uuid NOT NULL DEFAULT gen_random_uuid(),
            source               text NOT NULL,
            external_id          text NOT NULL,
            scope                text,
            url                  text NOT NULL,
            title                text NOT NULL,
            company              text,
            description          text,
            posted_at            timestamptz,
            updated_at           timestamptz,
            closes_at            timestamptz,
            locations            jsonb NOT NULL DEFAULT '[]'::jsonb,
            -- The place names, flattened, so they can be searched and indexed. Written by
            -- persist() rather than expressed over `locations`, because a generated column may
            -- only use immutable expressions and jsonb extraction here would be fragile.
            location_text        text NOT NULL DEFAULT '',
            salary_amount_min    numeric,
            salary_amount_max    numeric,
            salary_currency      text,
            salary_period        salary_period NOT NULL DEFAULT 'UNKNOWN',
            remote_hint          boolean,
            employment_type_hint text,
            agency_hint          boolean,
            language_hint        text,
            department_hint      text,
            content_hash         bytea NOT NULL,
            normalize_version    integer NOT NULL DEFAULT 0,
            listing_document_id  bigint REFERENCES source_document(id) ON DELETE SET NULL,
            detail_document_id   bigint REFERENCES source_document(id) ON DELETE SET NULL,
            first_seen_at        timestamptz NOT NULL DEFAULT now(),
            last_seen_at         timestamptz NOT NULL DEFAULT now(),
            closed_at            timestamptz,
            dedup_group          bytea,
            dedup_version        integer NOT NULL DEFAULT 0,

            search_de tsvector GENERATED ALWAYS AS (
                setweight(to_tsvector('german', coalesce(title, '')), 'A') ||
                setweight(to_tsvector('german', coalesce(company, '')), 'B') ||
                setweight(to_tsvector('german', coalesce(location_text, '')), 'C') ||
                setweight(to_tsvector('german', coalesce(description, '')), 'D')
            ) STORED,

            -- Title, company and place names, deliberately not descriptions. This index exists
            -- to match inside German compounds ('ingenieur' within 'Wirtschaftsingenieur') and to
            -- fold umlauts so 'munchen' finds 'München', both of which are title-and-place
            -- problems; the tsvector already stems descriptions. Including descriptions here
            -- would grow the GIN index by more than an order of magnitude for almost no recall.
            search_fold text GENERATED ALWAYS AS (
                lower(f_unaccent(
                    coalesce(title, '') || ' ' || coalesce(company, '') || ' '
                    || coalesce(location_text, '')
                ))
            ) STORED,

            CONSTRAINT job_provenance_uniq UNIQUE (source, external_id),
            CONSTRAINT job_public_id_uniq UNIQUE (public_id)
        )
        """
    )
    # Both search indexes are required and neither is sufficient alone: the tsvector misses
    # 'Ingenieur' inside 'Wirtschaftsingenieur', and trigram alone misses umlaut folding.
    op.execute("CREATE INDEX job_search_de_idx ON job USING gin (search_de)")
    op.execute("CREATE INDEX job_search_fold_trgm_idx ON job USING gin (search_fold gin_trgm_ops)")
    op.execute("CREATE INDEX job_open_posted_idx ON job (posted_at DESC NULLS LAST) "
               "WHERE closed_at IS NULL")
    # Serves lifecycle: "open postings in this scope not seen since the sweep began".
    op.execute("CREATE INDEX job_source_seen_idx ON job (source, scope, last_seen_at) "
               "WHERE closed_at IS NULL")
    op.execute("CREATE INDEX job_content_hash_idx ON job (content_hash)")
    op.execute("CREATE INDEX job_dedup_group_idx ON job (dedup_group) "
               "WHERE dedup_group IS NOT NULL")
    op.execute("CREATE INDEX job_company_idx ON job (company)")


    # Created alongside every job at derive_version 0, so refilling the derive queue after a
    # version bump is an index scan on one column instead of an anti-join against job.
    op.execute(
        """
        CREATE TABLE job_facet (
            job_id              bigint PRIMARY KEY REFERENCES job(id) ON DELETE CASCADE,
            derive_version      integer NOT NULL DEFAULT 0,
            countries           text[] NOT NULL DEFAULT '{}',
            regions             text[] NOT NULL DEFAULT '{}',
            cities              text[] NOT NULL DEFAULT '{}',
            work_mode           work_mode NOT NULL DEFAULT 'unknown',
            seniority           seniority NOT NULL DEFAULT 'unknown',
            employment_type     employment_type NOT NULL DEFAULT 'unknown',
            salary_min_eur_year numeric,
            salary_max_eur_year numeric,
            salary_annualised   boolean NOT NULL DEFAULT false,
            language            text,
            is_agency           boolean,
            skills              text[] NOT NULL DEFAULT '{}',
            derived_at          timestamptz
        )
        """
    )
    op.execute("CREATE INDEX job_facet_stale_idx ON job_facet (derive_version)")
    op.execute("CREATE INDEX job_facet_country_idx ON job_facet USING gin (countries)")
    op.execute("CREATE INDEX job_facet_city_idx ON job_facet USING gin (cities)")
    op.execute("CREATE INDEX job_facet_work_mode_idx ON job_facet (work_mode)")
    op.execute("CREATE INDEX job_facet_seniority_idx ON job_facet (seniority)")
    op.execute("CREATE INDEX job_facet_salary_idx ON job_facet (salary_min_eur_year)")
    op.execute("CREATE INDEX job_facet_skills_idx ON job_facet USING gin (skills)")

    # halfvec, not vector: fp16 halves both the column and the HNSW index with no measurable
    # recall loss at this dimensionality, and the index is the thing that has to fit in RAM.
    #
    # This table holds OPEN postings only -- closing a job deletes its row here. That makes the
    # table its own partial index, so the ANN index stays proportional to the live corpus rather
    # than to all history, with no denormalised is_open flag that could drift out of sync. The
    # vector is a pure function of the job's text, so reopening simply re-embeds.
    op.execute(
        """
        CREATE TABLE job_embedding (
            job_id            bigint PRIMARY KEY REFERENCES job(id) ON DELETE CASCADE,
            embedding_version text NOT NULL,
            embedding         halfvec(384) NOT NULL,
            embedded_at       timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX job_embedding_hnsw_idx ON job_embedding "
        "USING hnsw (embedding halfvec_cosine_ops)"
    )
    op.execute("CREATE INDEX job_embedding_version_idx ON job_embedding (embedding_version)")

    op.execute(
        """
        CREATE TABLE work_item (
            id             bigserial PRIMARY KEY,
            kind           work_kind NOT NULL,
            job_id         bigint NOT NULL REFERENCES job(id) ON DELETE CASCADE,
            target_version text NOT NULL,
            not_before     timestamptz NOT NULL DEFAULT now(),
            attempts       smallint NOT NULL DEFAULT 0,
            last_error     text,
            claimed_at     timestamptz,
            claimed_by     text,
            created_at     timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT work_item_kind_job_uniq UNIQUE (kind, job_id)
        )
        """
    )
    # Partial: claimed rows are not candidates, and excluding them keeps the index the size of
    # the actual backlog rather than the size of everything ever queued.
    op.execute(
        "CREATE INDEX work_item_ready_idx ON work_item (kind, not_before, id) "
        "WHERE claimed_at IS NULL"
    )
    op.execute(
        "CREATE INDEX work_item_claimed_idx ON work_item (claimed_at) "
        "WHERE claimed_at IS NOT NULL"
    )

    op.execute(
        """
        CREATE TABLE source_sweep (
            id                    bigserial PRIMARY KEY,
            source                text NOT NULL,
            started_at            timestamptz NOT NULL DEFAULT now(),
            finished_at           timestamptz,
            ok                    boolean,
            complete              boolean NOT NULL DEFAULT false,
            partitions_total      integer NOT NULL DEFAULT 0,
            partitions_done       integer NOT NULL DEFAULT 0,
            partitions_overflowed integer NOT NULL DEFAULT 0,
            documents_seen        integer NOT NULL DEFAULT 0,
            jobs_upserted         integer NOT NULL DEFAULT 0,
            jobs_closed           integer NOT NULL DEFAULT 0,
            error                 text
        )
        """
    )
    op.execute("CREATE INDEX source_sweep_recent_idx ON source_sweep (source, started_at DESC)")

    op.execute(
        """
        CREATE TABLE greenhouse_board (
            slug                 text PRIMARY KEY,
            enabled              boolean NOT NULL DEFAULT true,
            added_at             timestamptz NOT NULL DEFAULT now(),
            last_ok_at           timestamptz,
            last_error           text,
            consecutive_failures integer NOT NULL DEFAULT 0
        )
        """
    )

    op.execute(
        """
        CREATE TABLE app_user (
            id              bigserial PRIMARY KEY,
            username        text NOT NULL UNIQUE,
            email           text,
            password_hash   text NOT NULL,
            is_active       boolean NOT NULL DEFAULT true,
            failed_attempts integer NOT NULL DEFAULT 0,
            locked_until    timestamptz,
            created_at      timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE user_profile (
            user_id             bigint PRIMARY KEY REFERENCES app_user(id) ON DELETE CASCADE,
            version             integer NOT NULL DEFAULT 1,
            title               text NOT NULL DEFAULT '',
            years_experience    integer NOT NULL DEFAULT 0,
            objectives          text NOT NULL DEFAULT '',
            languages           text[] NOT NULL DEFAULT '{}',
            must_have           text[] NOT NULL DEFAULT '{}',
            deal_breakers       text[] NOT NULL DEFAULT '{}',
            keywords            text[] NOT NULL DEFAULT '{}',
            countries           text[] NOT NULL DEFAULT '{AT,DE,CH}',
            cities              text[] NOT NULL DEFAULT '{}',
            work_modes          text[] NOT NULL DEFAULT '{}',
            seniorities         text[] NOT NULL DEFAULT '{}',
            employment_types    text[] NOT NULL DEFAULT '{}',
            min_salary_eur_year numeric NOT NULL DEFAULT 0,
            retrieval_limit     integer NOT NULL DEFAULT 400,
            rerank_limit        integer NOT NULL DEFAULT 150,
            notify_threshold    smallint NOT NULL DEFAULT 70,
            updated_at          timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE user_llm_credential (
            user_id            bigint PRIMARY KEY REFERENCES app_user(id) ON DELETE CASCADE,
            api_key_encrypted  bytea NOT NULL,
            api_key_fingerprint text NOT NULL,
            model              text NOT NULL,
            provider_pin       text,
            monthly_budget_usd numeric NOT NULL DEFAULT 5,
            updated_at         timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE user_llm_spend (
            user_id      bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
            period_month date NOT NULL,
            tokens_in    bigint NOT NULL DEFAULT 0,
            tokens_out   bigint NOT NULL DEFAULT 0,
            cost_usd     numeric NOT NULL DEFAULT 0,
            calls        integer NOT NULL DEFAULT 0,
            updated_at   timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (user_id, period_month)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE user_job_match (
            user_id          bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
            job_id           bigint NOT NULL REFERENCES job(id) ON DELETE CASCADE,
            profile_version  integer NOT NULL,
            retrieval_score  real,
            dense_rank       integer,
            lexical_rank     integer,
            rule_verdict     rule_verdict NOT NULL DEFAULT 'unknown',
            rule_reason      text,
            llm_score        smallint,
            llm_reason       text,
            llm_red_flags    jsonb,
            scored_at        timestamptz,
            notified_at      timestamptz,
            state            user_state NOT NULL DEFAULT 'new',
            state_changed_at timestamptz,
            created_at       timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (user_id, job_id)
        )
        """
    )
    # Serves the recommendations page directly: one user, scored, best first.
    op.execute(
        "CREATE INDEX user_job_match_ranked_idx ON user_job_match "
        "(user_id, llm_score DESC NULLS LAST) WHERE llm_score IS NOT NULL"
    )
    op.execute("CREATE INDEX user_job_match_state_idx ON user_job_match (user_id, state)")
    op.execute(
        "CREATE INDEX user_job_match_unnotified_idx ON user_job_match (user_id, llm_score DESC) "
        "WHERE notified_at IS NULL AND llm_score IS NOT NULL"
    )
    op.execute("CREATE INDEX user_job_match_job_idx ON user_job_match (job_id)")

    op.execute(
        """
        CREATE TABLE llm_score_cache (
            content_hash    bytea NOT NULL,
            user_id         bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
            profile_version integer NOT NULL,
            score           smallint NOT NULL,
            reason          text NOT NULL DEFAULT '',
            red_flags       jsonb NOT NULL DEFAULT '[]'::jsonb,
            model           text NOT NULL,
            created_at      timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (content_hash, user_id, profile_version)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE user_query_expansion (
            user_id           bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
            profile_version   integer NOT NULL,
            expansion_version integer NOT NULL,
            queries           text[] NOT NULL DEFAULT '{}',
            created_at        timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (user_id, profile_version, expansion_version)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE pipeline_schedule (
            id          smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
            enabled     boolean NOT NULL DEFAULT true,
            run_hour    smallint NOT NULL DEFAULT 7,
            run_minute  smallint NOT NULL DEFAULT 0,
            updated_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("INSERT INTO pipeline_schedule (id) VALUES (1)")

    op.execute(
        """
        CREATE TABLE pipeline_run (
            id          bigserial PRIMARY KEY,
            trigger     run_trigger NOT NULL,
            status      run_status NOT NULL DEFAULT 'queued',
            only_source text,
            backfill    boolean NOT NULL DEFAULT false,
            attempts    smallint NOT NULL DEFAULT 0,
            queued_at   timestamptz NOT NULL DEFAULT now(),
            not_before  timestamptz NOT NULL DEFAULT now(),
            started_at  timestamptz,
            finished_at timestamptz,
            report      jsonb,
            error       text
        )
        """
    )
    op.execute(
        "CREATE INDEX pipeline_run_pending_idx ON pipeline_run (not_before, id) "
        "WHERE status = 'queued'"
    )
    op.execute("CREATE INDEX pipeline_run_recent_idx ON pipeline_run (queued_at DESC)")


def downgrade() -> None:
    raise NotImplementedError("v2 is the initial schema; recreate the database instead.")
